name: docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-audit

      - name: Build VuePress site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: docs/.vuepress/dist
          fqdn: roserepo.meslzy.com
          target_branch: pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}